# Use the latest image available.
image: Visual Studio 2017
version: 0.1.{build}

install:
  # Install Rust through rustup
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain nightly-2018-08-19 --default-host nightly-i686-pc-windows-msvc
  # Add to path
  - set PATH=%USERPROFILE%/.cargo/bin;%PATH%
  # Print the installed versions
  - rustc -vV
  - cargo -vV
  - rustup self update
  - rustup update

build_script:
  - cargo +nightly fix --edition
  - cargo +nightly build --release --target nightly-i686-pc-windows-msvc --verbose

# Save the built DLL.
artifacts:
- path: target\nightly-i686-pc-windows-msvc\release\d3d9.dll
  name: D3D9

cache:
  - target
  - D:\Users\appveyor\.cargo\
  - D:\Users\appveyor\.rustup\
